# An example of a services.yaml file in an extension

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $defaultLocale: '%locale%'

  Bolt\TntSearch\Controller\:
    resource: '../../vendor/bolt/tnt-search-engine/src/Controller/'
    tags: ['controller.service_arguments']

